var renderDefaults = Object.create(null);
extend(renderDefaults, {
    btn: button,
    button,
    a: button,
    go: zimoli.go,
    care,
    cast,
    input,
    padding,
    block,
    grid,
    lattice,
    list,
    xlist: list,
    ylist: list,
    vbox,
    hbox: vbox,
    xbox: vbox,
    ybox: vbox,
    radio,
    checker,
    checkbox,
    select,
    view,
    field,
    model,
    drop,
    delete: drop,
    close: drop,
    remove: drop,
    pic: img,
    image,
    back,
    switch: swap,
    swap,
    password,
    table,
});