var s = speed();
var id = 0;
var passed = +new Date;
var test = async function (wait, write = '') {
    var _id = ++id;
    await new Promise(ok => setTimeout(ok, wait));
    if (write) var read = s(write);
    else var read = s();
    var now = +new Date;
    if (passed) var waited = now - passed;
    else waited = 0;
    passed = now;
    console.log({ _id, wait, waited, read, write });
    return read > 0.1;
};
await test(10, 20)
await test(20, 30);
await test(20, 30);
await test(20, 30);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
await test(20);
while (await test(20));
