assert(renderExpress("[].a"), "[].a")
assert(renderExpress("a?b:c"), "a?b:c")
assert(renderExpress("a?"), "(typeof a==='undefined'||a===null?void 0:a)")
assert(renderExpress("b+a?."), "b+(typeof a==='undefined'||a===null?void 0:a)")
assert(renderExpress("a?.+b"), "(typeof a==='undefined'||a===null?void 0:a)+b")
assert(renderExpress("a?.()"), "(typeof a==='undefined'||a===null?void 0:a())")
assert(renderExpress("a.b?.()"), `(function(c,a,_){a=c.b;return a==_?_:a["call"](c)}(a))`)
assert(renderExpress("a[['a[']][]?.()"), `(function(c,a,_){a=c[];return a==_?_:a["call"](c)}(a[['a[']]))`)
assert(renderExpress("a?.b?.()"), `(typeof a==='undefined'||a===null?void 0:function(a,c,_){if(a==_)return;c=a,a=c.b;if(a==_)return;a=a["call"](c);return a}(a))`)
assert(renderExpress("[].a?.()"), `(function(c,a,_){a=c.a;return a==_?_:a["call"](c)}([]))`)// 已支持在?.()的函数中访问this
assert(renderExpress("[].a?.b?.c?.()"), `(function(a,c,_){if(a==_)return;a=a.b;if(a==_)return;c=a,a=c.c;if(a==_)return;a=a["call"](c);return a}([].a))`)
assert(renderExpress("a??b"), "(typeof a!=='undefined'&&a!==null?a:b)")
assert(renderExpress("a?.b??b?.c", false), "(function(b0){b0=a==null?void 0:a.b;if(b0!=null)return b0;return b==null?void 0:b.c}())")

assert(renderExpress("[]?.a"), "(function(a,_){return a==_?_:a.a}([]))")
assert(renderExpress("[]?.()"), "(function(a,_){return a==_?_:a()}([]))")
assert(renderExpress("[]?.[]"), "(function(a,_){return a==_?_:a[]}([]))")
assert(renderExpress("a['a?.a']"), "a['a?.a']")
assert(renderExpress("a?.['a?.a']?.b"), "(typeof a==='undefined'||a===null?void 0:function(a,_){if(a==_)return;a=a['a?.a'];if(a==_)return;a=a.b;return a}(a))")
