"use strict";
(function (Token) {
    Token[Token["BooleanLiteral"] = 1] = "BooleanLiteral";
    Token[Token["EOF"] = 2] = "EOF";
    Token[Token["Identifier"] = 3] = "Identifier";
    Token[Token["Keyword"] = 4] = "Keyword";
    Token[Token["NullLiteral"] = 5] = "NullLiteral";
    Token[Token["NumericLiteral"] = 6] = "NumericLiteral";
    Token[Token["Punctuator"] = 7] = "Punctuator";
    Token[Token["StringLiteral"] = 8] = "StringLiteral";
    Token[Token["RegularExpression"] = 9] = "RegularExpression";
    Token[Token["Template"] = 10] = "Template";
})(exports.Token || (exports.Token = {}));
var Token = exports.Token;;
exports.TokenName = {};
exports.TokenName[Token.BooleanLiteral] = 'Boolean';
exports.TokenName[Token.EOF] = '<end>';
exports.TokenName[Token.Identifier] = 'Identifier';
exports.TokenName[Token.Keyword] = 'Keyword';
exports.TokenName[Token.NullLiteral] = 'Null';
exports.TokenName[Token.NumericLiteral] = 'Numeric';
exports.TokenName[Token.Punctuator] = 'Punctuator';
exports.TokenName[Token.StringLiteral] = 'String';
exports.TokenName[Token.RegularExpression] = 'RegularExpression';
exports.TokenName[Token.Template] = 'Template';