#!/usr/bin/env bash
if [ -L $0 ]
then
__dirname=`dirname $(readlink $0)`
else
__dirname=`dirname $0`
fi
cd $__dirname/..
clear
pwd
coms_path=./coms,
page_path=./coms
public_path=./public
export_to=node
page=./
app=efront/index.js
extt=.js
coms=./
# libs_path=./
# libs=typescript,esprima,escodegen,esmangle,pngjs,less-node
destpath=efront.js
rm -rf "$public_path"
node coms/efront publish
